# Generated by Django 5.2.8 on 2025-11-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
