# Generated by Django 5.2.8 on 2025-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artsubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsubtype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_arttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arttype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
