# Generated by Django 5.2.8 on 2025-11-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_artsubtype_tbl_arttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_artsubtype',
        ),
    ]
