# Generated by Django 5.2.8 on 2025-11-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_artsubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artsubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artsubtype_name', models.CharField(max_length=50)),
                ('arttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_arttype')),
            ],
        ),
    ]
