# Generated by Django 5.2.8 on 2025-11-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_artsubtype'),
        ('Guest', '0003_tbl_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(max_length=50)),
                ('artwork_details', models.CharField(max_length=50)),
                ('artwork_photo', models.FileField(upload_to='Assets/ArtistDocs/')),
                ('artwork_price', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
                ('artsubtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_artsubtype')),
            ],
        ),
    ]
