# Generated by Django 5.2.8 on 2025-11-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/ArtworkDocs/')),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artwork')),
            ],
        ),
    ]
