# Generated by Django 5.2.8 on 2025-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_dob',
            field=models.DateField(),
        ),
    ]
