# Generated by Django 5.2.8 on 2025-11-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_artsubtype'),
        ('Guest', '0002_alter_tbl_user_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('artist_email', models.CharField(max_length=50)),
                ('artist_contact', models.CharField(max_length=50)),
                ('artist_address', models.CharField(max_length=50)),
                ('artist_photo', models.FileField(upload_to='Assets/ArtistDocs/')),
                ('artist_proof', models.FileField(upload_to='Assets/ArtistDocs/')),
                ('artist_password', models.CharField(max_length=50)),
                ('artist_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
