# Generated by Django 5.2.8 on 2026-01-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_dob',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_gender',
        ),
    ]
