# Generated by Django 5.2.8 on 2026-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_tbl_user_user_dob_remove_tbl_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_password',
            field=models.CharField(max_length=200),
        ),
    ]
