# Generated by Django 5.2.8 on 2025-12-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_customization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customization',
            old_name='customization_datails',
            new_name='customization_details',
        ),
    ]
