# Generated by Django 5.2.8 on 2025-12-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_customization_datails_tbl_customization_customization_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customization',
        ),
    ]
