# Generated by Django 5.2.8 on 2025-12-04 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_artsubtype'),
        ('Guest', '0003_tbl_artist'),
        ('User', '0004_delete_tbl_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizaion_date', models.DateField(auto_now_add=True)),
                ('customization_status', models.IntegerField(default=0)),
                ('customization_details', models.CharField(max_length=50)),
                ('customization_file', models.FileField(upload_to='Assets/CustomDocs/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
                ('artsubtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_artsubtype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
