# Generated by Django 5.2.8 on 2025-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_booking_tbl_comment_tbl_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customization',
            name='customization_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
