# Generated by Django 5.2.8 on 2025-12-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_artist'),
        ('User', '0008_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
