# Generated by Django 5.2.8 on 2025-12-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_artist'),
        ('User', '0009_alter_tbl_feedback_artist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('artist_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_from', to='Guest.tbl_artist')),
                ('artist_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_to', to='Guest.tbl_artist')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
